// demo 帳號的資料常數；寫入邏輯在 seed.ts
// 書目、封面、頁數取自站內書目搜尋；關鍵字的年份、座標、維基連結 2026-09 逐筆對過維基百科與 Wikidata

export const TYPES: Record<string, string[]> = {
  商業: ["管理", "個人成長", "理財"],
  人文社科: ["心理學"],
  文學: ["小說", "散文"],
};

export const ATTRIBUTES = ["小說", "論述", "散文"];

type Status = "完成" | "進行" | "想要";

type Book = {
  title: string;
  creator: string;
  publisher: string;
  topic: string; // 領域/子領域，對 TYPES
  attribute: string;
  amount: number | null; // 頁數；查不到就留空，不編
  coverUrl: string;
  externalId: string; // ISBN-13；不確定就留空
  body: string;
  status: Status;
  keywords: string[]; // 對 KEYWORDS 的 title
};

const taaze = (sc: string) =>
  `https://media.taaze.tw/showProdImage.html?sc=${sc}&width=200&height=283`;

export const BOOKS: Book[] = [
  {
    title: "原子習慣：細微改變帶來巨大成就的實證法則",
    creator: "詹姆斯．克利爾",
    publisher: "方智",
    topic: "商業/個人成長",
    attribute: "論述",
    amount: 304,
    coverUrl: taaze("11100876604"),
    externalId: "",
    body: "主張微小習慣會像複利一樣累積成巨大改變，並提出讓好習慣顯而易見、有吸引力、簡便易行、令人滿足的四大法則。",
    status: "完成",
    keywords: ["習慣", "複利"],
  },
  {
    title: "管理（修訂版）",
    creator: "彼得．杜拉克",
    publisher: "遠流",
    topic: "商業/管理",
    attribute: "論述",
    amount: null,
    coverUrl: "https://cdn.readmoo.com/cover/ll/jlbnqf9.jpg?v=1757402529",
    externalId: "9786267508237",
    body: "杜拉克管理思想的整理修訂本，涵蓋企業的目的與使命、目標管理、知識工作者與組織的社會責任。",
    status: "完成",
    keywords: ["杜拉克", "目標管理"],
  },
  {
    title: "從A到A+：企業從優秀到卓越的奧祕",
    creator: "詹姆．柯林斯",
    publisher: "遠流",
    topic: "商業/管理",
    attribute: "論述",
    amount: 400,
    coverUrl: "https://cdn.readmoo.com/cover/fi/hl78mb8.jpg?v=1661310076",
    externalId: "9789573287032",
    body: "研究團隊比較由優秀躍升卓越的企業與對照組，歸納出第五級領導、先找對人、刺蝟原則等共同特質。",
    status: "完成",
    keywords: ["杜拉克"],
  },
  {
    title: "葛洛夫給經理人的第一課",
    creator: "安德魯．葛洛夫",
    publisher: "遠流",
    topic: "商業/管理",
    attribute: "論述",
    amount: 292,
    coverUrl: taaze("11100871995"),
    externalId: "9789573284925",
    body: "英特爾前執行長以早餐店比喻生產流程，講解產出導向的管理、一對一會議與績效評估等經理人實務。",
    status: "完成",
    keywords: ["葛洛夫", "英特爾", "矽谷"],
  },
  {
    title: "創新的兩難",
    creator: "克雷頓．克里斯汀生",
    publisher: "商周出版",
    topic: "商業/管理",
    attribute: "論述",
    amount: 304,
    coverUrl: taaze("11100156073"),
    externalId: "",
    body: "說明領先企業為何在傾聽主流顧客、追求高利潤的同時，被從低階市場切入的破壞性技術取代。",
    status: "完成",
    keywords: ["克里斯汀生", "破壞式創新"],
  },
  {
    title: "精實創業：用小實驗玩出大事業",
    creator: "艾瑞克．萊斯",
    publisher: "行人",
    topic: "商業/管理",
    attribute: "論述",
    amount: 360,
    coverUrl: "https://cdn.readmoo.com/cover/61/c085gac.jpg?v=1525245334",
    externalId: "9789869546232",
    body: "把科學實驗的方法用在新創，以最小可行產品與「開發－測量－學習」循環驗證假設，再決定堅持或轉向。",
    status: "完成",
    keywords: ["最小可行產品", "矽谷"],
  },
  {
    title: "目標：簡單有效的常識管理",
    creator: "高德拉特",
    publisher: "天下文化",
    topic: "商業/管理",
    attribute: "小說",
    amount: 584,
    coverUrl: taaze("11100033075"),
    externalId: "",
    body: "以一位廠長設法挽救工廠的小說形式，介紹找出並管理瓶頸的限制理論。",
    status: "完成",
    keywords: ["限制理論"],
  },
  {
    title: "零規則",
    creator: "里德．海斯汀、艾琳．梅爾",
    publisher: "天下雜誌",
    topic: "商業/管理",
    attribute: "論述",
    amount: 336,
    coverUrl: taaze("11100921317"),
    externalId: "9789863986102",
    body: "Netflix 共同創辦人與商學院教授合寫，說明提高人才密度、坦誠回饋、逐步取消控管規則的企業文化。",
    status: "想要",
    keywords: ["Netflix", "矽谷"],
  },
  {
    title: "與成功有約：高效能人士的七個習慣",
    creator: "史蒂芬．柯維、西恩．柯維",
    publisher: "天下文化",
    topic: "商業/個人成長",
    attribute: "論述",
    amount: 520,
    coverUrl: taaze("11100921809"),
    externalId: "9789865535667",
    body: "提出由內而外的個人效能架構，歸納為主動積極、以終為始、要事第一等七個習慣。",
    status: "完成",
    keywords: ["習慣"],
  },
  {
    title: "Deep Work深度工作力",
    creator: "卡爾．紐波特",
    publisher: "時報出版",
    topic: "商業/個人成長",
    attribute: "論述",
    amount: 320,
    coverUrl: taaze("11100967753"),
    externalId: "",
    body: "主張不受干擾的專注工作在知識經濟中愈來愈稀有也愈有價值，並提出培養深度工作的四項規則。",
    status: "進行",
    keywords: ["刻意練習"],
  },
  {
    title: "刻意練習",
    creator: "安德斯．艾瑞克森、羅伯特．普爾",
    publisher: "方智",
    topic: "商業/個人成長",
    attribute: "論述",
    amount: 320,
    coverUrl: taaze("11100815405"),
    externalId: "9789861754604",
    body: "研究專業表現的心理學家說明，傑出表現來自有明確目標、即時回饋、持續走出舒適圈的練習，而非天生才能。",
    status: "完成",
    keywords: ["刻意練習"],
  },
  {
    title: "心態致勝：全新成功心理學",
    creator: "卡蘿．杜維克",
    publisher: "天下文化",
    topic: "人文社科/心理學",
    attribute: "論述",
    amount: null,
    coverUrl: taaze("14100023358"),
    externalId: "",
    body: "區分定型心態與成長心態，說明相信能力可以培養的人如何面對挑戰、努力與失敗。",
    status: "完成",
    keywords: ["杜維克"],
  },
  {
    title: "致富心態",
    creator: "摩根．豪瑟",
    publisher: "天下文化",
    topic: "商業/理財",
    attribute: "論述",
    amount: 336,
    coverUrl: "https://res2.pubu.tw/docs/283437/34306/uRQcKV_l.jpg",
    externalId: "9786263550551",
    body: "以二十則短篇說明理財的成敗多半取決於行為與心態，而不是知識或智力。",
    status: "完成",
    keywords: ["複利", "行為經濟學"],
  },
  {
    title: "漫步華爾街",
    creator: "墨基爾",
    publisher: "天下文化",
    topic: "商業/理財",
    attribute: "論述",
    amount: 404,
    coverUrl: taaze("11100033086"),
    externalId: "",
    body: "介紹股票評價理論與效率市場假說，主張一般投資人以低成本的指數型基金長期投資。",
    status: "完成",
    keywords: ["華爾街", "指數型基金"],
  },
  {
    title: "快思慢想",
    creator: "康納曼",
    publisher: "天下文化",
    topic: "人文社科/心理學",
    attribute: "論述",
    amount: 576,
    coverUrl: taaze("11101014773"),
    externalId: "",
    body: "以直覺快速的系統一與費力緩慢的系統二，解釋人在判斷與決策中的各種偏誤。",
    status: "完成",
    keywords: ["康納曼", "行為經濟學"],
  },
  {
    title: "誰說人是理性的！",
    creator: "丹．艾瑞利",
    publisher: "天下文化",
    topic: "人文社科/心理學",
    attribute: "論述",
    amount: 329,
    coverUrl: taaze("11100033184"),
    externalId: "",
    body: "以一系列實驗說明人在定價、免費、社會規範等情境下，會以可預測的方式做出不理性的決定。",
    status: "完成",
    keywords: ["行為經濟學"],
  },
  {
    title: "目送",
    creator: "龍應台",
    publisher: "時報出版",
    topic: "文學/散文",
    attribute: "散文",
    amount: 360,
    coverUrl: taaze("11100982838"),
    externalId: "9786263353916",
    body: "龍應台的散文集，書寫父親老去、母親失智與兒子長大，談親情、離別與生死。",
    status: "完成",
    keywords: ["龍應台", "散文"],
  },
  {
    title: "雅舍小品",
    creator: "梁實秋",
    publisher: "正中書局",
    topic: "文學/散文",
    attribute: "散文",
    amount: 385,
    coverUrl: taaze("11100244513"),
    externalId: "",
    body: "梁實秋的小品文集，以幽默平實的筆調寫衣食住行、人情往來等日常瑣事。",
    status: "完成",
    keywords: ["梁實秋", "散文"],
  },
  {
    title: "京都一年",
    creator: "林文月",
    publisher: "三民書局",
    topic: "文學/散文",
    attribute: "散文",
    amount: 288,
    coverUrl: taaze("11100878222"),
    externalId: "9789571476582",
    body: "林文月旅居京都研究期間寫下的散文，記述當地的節慶、寺院庭園、市場與四季生活。",
    status: "完成",
    keywords: ["林文月", "京都"],
  },
  {
    title: "關於跑步，我說的其實是……",
    creator: "村上春樹",
    publisher: "時報出版",
    topic: "文學/散文",
    attribute: "散文",
    amount: null,
    coverUrl: taaze("11100210256"),
    externalId: "",
    body: "村上春樹以長年跑馬拉松的經驗為主軸，談跑步、寫小說與日復一日的紀律。",
    status: "進行",
    keywords: ["村上春樹"],
  },
  {
    title: "美的覺醒",
    creator: "蔣勳",
    publisher: "遠流",
    topic: "文學/散文",
    attribute: "散文",
    amount: 324,
    coverUrl: "https://cdn.readmoo.com/cover/8f/ce9cl86.jpg?v=1617959265",
    externalId: "9789573259268",
    body: "蔣勳從視覺、聽覺、嗅覺、味覺、觸覺五種感官出發，談如何在日常生活中重新感受美。",
    status: "進行",
    keywords: ["蔣勳", "散文"],
  },
  {
    title: "湖濱散記",
    creator: "亨利．大衛．梭羅",
    publisher: "時報出版",
    topic: "文學/散文",
    attribute: "散文",
    amount: 370,
    coverUrl: taaze("11100899035"),
    externalId: "9789571380803",
    body: "梭羅記述在瓦爾登湖畔自建小屋獨居兩年多的生活，思索簡樸、自然與自立。",
    status: "完成",
    keywords: ["梭羅", "瓦爾登湖"],
  },
  {
    title: "小王子",
    creator: "安東尼．聖修伯里",
    publisher: "晨星出版",
    topic: "文學/小說",
    attribute: "小說",
    amount: 245,
    coverUrl: taaze("14100028071"),
    externalId: "",
    body: "飛行員在撒哈拉沙漠迫降，遇見來自小行星的小王子，聽他講述拜訪各個星球的見聞。",
    status: "完成",
    keywords: ["聖修伯里", "撒哈拉沙漠"],
  },
  {
    title: "解憂雜貨店",
    creator: "東野圭吾",
    publisher: "皇冠",
    topic: "文學/小說",
    attribute: "小說",
    amount: 352,
    coverUrl: taaze("11100665527"),
    externalId: "",
    body: "一間能與過去通信的雜貨店，把幾位來信求助的人跨越數十年的人生串在一起。",
    status: "想要",
    keywords: ["東野圭吾"],
  },
  {
    title: "哈利波特（1）：神秘的魔法石",
    creator: "J.K. 羅琳",
    publisher: "皇冠",
    topic: "文學/小說",
    attribute: "小說",
    amount: 352,
    coverUrl: "https://res3.pubu.tw/docs/518462/46931/jt780S_l.jpg",
    externalId: "9789573335566",
    body: "孤兒哈利在十一歲生日得知自己是巫師，進入霍格華茲魔法學校，並揭開魔法石的祕密。",
    status: "想要",
    keywords: ["羅琳", "奇幻"],
  },
  {
    title: "牧羊少年奇幻之旅",
    creator: "保羅．科爾賀",
    publisher: "時報出版",
    topic: "文學/小說",
    attribute: "小說",
    amount: 240,
    coverUrl: taaze("11100966192"),
    externalId: "",
    body: "西班牙牧羊少年為了一個反覆出現的夢，離鄉橫越沙漠，前往埃及金字塔尋找寶藏。",
    status: "完成",
    keywords: ["科爾賀", "撒哈拉沙漠"],
  },
];

export const REREADS = [0, 22]; // 原子習慣、小王子

type Writing = {
  title: string;
  kind: "心得" | "思緒";
  book: number | null; // 出處，對 BOOKS 的索引
  topic: string;
  keywords: string[];
  body: string;
};

export const WRITINGS: Writing[] = [
  {
    title: "讀《原子習慣》：複利是怎麼發生的",
    kind: "心得",
    book: 0,
    topic: "商業/個人成長",
    keywords: ["習慣", "複利"],
    body: "一天進步 1% 聽起來很小，放到一年就看得見。最有用的是它把焦點從目標挪到系統。",
  },
  {
    title: "杜拉克說的「創造顧客」",
    kind: "心得",
    book: 1,
    topic: "商業/管理",
    keywords: ["杜拉克", "目標管理"],
    body: "以前以為企業的目的是獲利，讀完才懂獲利是結果，顧客才是起點。",
  },
  {
    title: "《快思慢想》的兩個系統，我用了三年才懂",
    kind: "心得",
    book: 14,
    topic: "人文社科/心理學",
    keywords: ["康納曼", "行為經濟學"],
    body: "系統一不是笨，是快。知道它快，就知道什麼時候該放慢一點。",
  },
  {
    title: "一對一會議該聊什麼",
    kind: "心得",
    book: 3,
    topic: "商業/管理",
    keywords: ["葛洛夫", "英特爾"],
    body: "葛洛夫把一對一會議當成部屬的時間。照著試了一個月，團隊的問題提早浮上來了。",
  },
  {
    title: "跑步和寫作是同一種練習",
    kind: "心得",
    book: 19,
    topic: "文學/散文",
    keywords: ["村上春樹", "刻意練習"],
    body: "每天跑一點、每天寫一點，靠的都是固定節奏。這個月開始晨跑，寫作排在跑完之後。",
  },
  {
    title: "散文要怎麼讀才不無聊",
    kind: "思緒",
    book: null,
    topic: "文學/散文",
    keywords: ["散文", "梁實秋", "蔣勳"],
    body: "散文沒有情節推著走，慢慢讀反而好看。一天一篇，像跟作者喝一杯茶。",
  },
  {
    title: "理財書為什麼都在講心態",
    kind: "思緒",
    book: 12,
    topic: "商業/理財",
    keywords: ["複利", "指數型基金", "華爾街"],
    body: "工具講得都差不多，差別在能不能長期不動。這樣想，理財其實是一門耐心的功課。",
  },
  {
    title: "京都的慢",
    kind: "心得",
    book: 18,
    topic: "文學/散文",
    keywords: ["京都", "林文月"],
    body: "林文月寫的都是小事：市場、寺院、換季。讀完也想找一座城市慢慢住上一年。",
  },
  {
    title: "一年讀了幾本書這件事",
    kind: "思緒",
    book: null,
    topic: "商業/個人成長",
    keywords: ["習慣"],
    body: "數字好記，更值得記的是哪一本讓生活多了一點什麼。",
  },
];

export const QUOTES = [
  { book: 0, text: "你不會升到目標的高度，你會掉到系統的水準。", locator: "第一章" },
  { book: 1, text: "企業的目的只有一個正確而有效的定義：創造顧客。", locator: "" },
  {
    book: 16,
    text: "我慢慢地、慢慢地了解到，所謂父女母子一場，只不過意味著，你和他的緣分就是今生今世不斷地在目送他的背影漸行漸遠。",
    locator: "〈目送〉",
  },
  { book: 12, text: "財富是你看不見的東西。", locator: "" },
  {
    book: 21,
    text: "我到林中去，因為我希望從容不迫地生活。",
    locator: "〈我生活的地方；我為何生活〉",
  },
  { book: 22, text: "真正重要的東西，用眼睛是看不見的。", locator: "第二十一章" },
  {
    book: 25,
    text: "當你真心渴望某樣東西時，整個宇宙都會聯合起來幫助你完成。",
    locator: "第一部",
  },
];

export const VOCABULARY = [
  {
    book: 0,
    word: "compound",
    pronunciation: "ˈkɑmpaʊnd",
    translation: "複利、累積",
    example: "Habits are the compound interest of self-improvement.",
    exampleTranslation: "習慣是自我提升的複利。",
  },
  {
    book: 14,
    word: "heuristic",
    pronunciation: "hjʊˈrɪstɪk",
    translation: "捷思",
    example: "People rely on heuristics when they have to decide quickly.",
    exampleTranslation: "人在需要快速決定時會依賴捷思。",
  },
  {
    book: 4,
    word: "disruptive",
    pronunciation: "dɪsˈrʌptɪv",
    translation: "破壞性的",
    example: "Disruptive technologies often start in markets that leaders ignore.",
    exampleTranslation: "破壞性技術常從領先者忽略的市場起步。",
  },
  {
    book: 10,
    word: "deliberate",
    pronunciation: "dɪˈlɪbərət",
    translation: "刻意的、深思熟慮的",
    example: "Deliberate practice targets skills just beyond your current level.",
    exampleTranslation: "刻意練習瞄準略高於目前程度的技巧。",
  },
  {
    book: 11,
    word: "mindset",
    pronunciation: "ˈmaɪndˌsɛt",
    translation: "心態",
    example: "A growth mindset treats failure as information.",
    exampleTranslation: "成長心態把失敗當成資訊。",
  },
];
